name: Compiler Job Test
description: Create a draft PDF for an Open Journals paper
inputs:
  repo:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: main
  paper-path:
    description: >-
        Path to the main paper Markdown file, relative to the
        project's root directory.
    required: false
    default: 'paper.md'
runs:
branding:
  icon: file-text
  color: blue