name: Compiler Job Test
description: Create a draft PDF for an Open Journals paper
inputs:
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
  journal:
    description: The journal template to use for the paper. Default is 'joss'.
    required: false
    default: joss
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Find paper file
      id: paper-finder
      shell: bash
      env:
        REPO_URL: ${{ inputs.repository_url }}
        PAPER_BRANCH: ${{ inputs.branch }}
      run: |
        echo "::set-output name=paper_file_path::$(ruby ${{ github.action_path }}/find_paper.rb)"
    - name: Check result
      shell: bash
      run: |
        echo "Paper path is: ${{ steps.paper-finder.outputs.paper_file_path }}"
    - name: Build draft PDF
      uses: openjournals/openjournals-draft-action@master
      with:
        journal: ${{ inputs.journal }}
        paper-path: ${{ steps.paper-finder.outputs.paper_file_path }}

branding:
  icon: file-text
  color: blue
