name: Compiler Job Test
description: Create a draft PDF for an Open Journals paper
inputs:
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
outputs:
  paper_path:
    description: "Path to the paper file to compile"
    value: ${{ steps.paper-finder.outputs.paper_file_path }}
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Find paper file
      id: paper-finder
      shell: bash
      env:
        REPO_URL: ${{ github.event.inputs.repository_url }}
        PAPER_BRANCH: ${{ github.event.inputs.branch }}
      run: |
        echo "::set-output name=paper_file_path::$(ruby ${{ github.action_path }}/find_paper.rb)"
        export REPO_PAPER_PATH=$(ruby ${{ github.action_path }}/find_paper.rb)
    - name: Check result
      shell: bash
      run: |
        echo $REPO_PAPER_PATH
        echo ${{ outputs.paper_path.value }}

branding:
  icon: file-text
  color: blue
